# Generated by Django 6.0.6 on 2026-07-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_order_delivered_at_order_ready_at_order_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('guide_image', models.ImageField(blank=True, null=True, upload_to='measurement_guides/')),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'measurement_master',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='measurement_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'measurement_video',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='necks/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'neck_type',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SleeveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sleeves/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sleeve_type',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CommonMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_measurements', to='measurements.measurementmaster')),
            ],
            options={
                'db_table': 'common_measurement',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_measurements', to='orders.order')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_measurements', to='measurements.measurementmaster')),
            ],
            options={
                'db_table': 'customer_measurement',
                'ordering': ['order'],
                'unique_together': {('order', 'measurement')},
            },
        ),
        migrations.CreateModel(
            name='NeckMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neck_measurements', to='measurements.measurementmaster')),
                ('neck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.necktype')),
            ],
            options={
                'db_table': 'neck_measurement',
                'ordering': ['display_order'],
                'unique_together': {('neck_type', 'measurement')},
            },
        ),
        migrations.CreateModel(
            name='SleeveMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_measurements', to='measurements.measurementmaster')),
                ('sleeve_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.sleevetype')),
            ],
            options={
                'db_table': 'sleeve_measurement',
                'ordering': ['display_order'],
                'unique_together': {('sleeve_type', 'measurement')},
            },
        ),
    ]
