# Generated by Django 6.0.6 on 2026-07-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_designimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.design')),
            ],
            options={
                'unique_together': {('design', 'size', 'color')},
            },
        ),
    ]
