# Generated by Django 6.0.6 on 2026-08-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_designvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_customizable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='collectioncategory',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='collectioncategory',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='design',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='design',
            name='is_new_arrival',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='designvariant',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
