# Generated by Django 6.0.6 on 2026-08-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_design_is_customizable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='category',
        ),
        migrations.AddField(
            model_name='design',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='catalog.section'),
            preserve_default=False,
        ),
    ]
