# Generated by Django 6.0.6 on 2026-08-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_design_category_design_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='collection_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='catalog.collectioncategory'),
        ),
    ]
