# Generated by Django 6.0.6 on 2026-08-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_design_collection_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='collection_category',
        ),
    ]
