# Generated by Django 6.0.6 on 2026-07-13 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_ACCEPTED', 'Order Accepted'), ('ORDER_STARTED', 'Tailoring Started'), ('ORDER_READY', 'Order Ready'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_RECEIVED', 'Payment Received'), ('NEW_REVIEW', 'New Review')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
