# Generated by Django 6.0.6 on 2026-08-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_ACCEPTED', 'Order Accepted'), ('ORDER_STARTED', 'Tailoring Started'), ('ORDER_READY', 'Order Ready'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_RECEIVED', 'Payment Received'), ('NEW_REVIEW', 'New Review'), ('CUSTOM_DESIGN_REQUEST', 'Custom Design Request')], max_length=30),
        ),
    ]
