# Generated by Django 6.0.6 on 2026-08-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_charge_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
