# Generated by Django 6.0.6 on 2026-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
