# Generated by Django 6.0.6 on 2026-08-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_shippingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='pincode',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
