# Generated by Django 6.0.6 on 2026-07-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('FABRIC', 'Fabric'), ('THREAD', 'Thread'), ('BUTTON', 'Button'), ('ZIP', 'Zip'), ('LACE', 'Lace'), ('LINING', 'Lining'), ('ELASTIC', 'Elastic'), ('HOOK', 'Hook'), ('OTHER', 'Other')], max_length=20)),
                ('unit', models.CharField(choices=[('METER', 'Meter'), ('PIECE', 'Piece'), ('BOX', 'Box'), ('KG', 'Kilogram'), ('ROLL', 'Roll')], max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='boutiques.boutique')),
            ],
            options={
                'ordering': ['item_name'],
                'unique_together': {('boutique', 'item_name')},
            },
        ),
    ]
