# Generated by Django 6.0.6 on 2026-07-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_designvariant'),
        ('customers', '0001_initial'),
        ('orders', '0007_order_delivered_at_order_ready_at_order_started_at'),
        ('reviews', '0002_rename_review_review_review_text_review_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('customer', 'order', 'design')},
        ),
    ]
