# Generated by Django 6.0.6 on 2026-07-26 01:09

from django.db import migrations, models


def mark_existing_payments_success(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")

    Payment.objects.all().update(status="SUCCESS")


def reverse_existing_payments(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")

    Payment.objects.all().update(status="CREATED")


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
            ),
        ),

        migrations.AddField(
            model_name="payment",
            name="gateway_order_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
            ),
        ),

        migrations.AddField(
            model_name="payment",
            name="gateway_payment_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
            ),
        ),

        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("FULL", "Full Payment"),
                    ("ADVANCE", "Advance Payment"),
                    ("BALANCE", "Balance Payment"),
                ],
                default="FULL",
                max_length=20,
            ),
        ),

        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),

        migrations.RunPython(
            mark_existing_payments_success,
            reverse_existing_payments,
        ),
    ]