# Generated by Django 6.0.6 on 2026-07-16 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutiques', '0001_initial'),
        ('employees', '0002_employee_user'),
        ('orders', '0007_order_delivered_at_order_ready_at_order_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CUTTING', 'Cutting'), ('STITCHING', 'Stitching'), ('TRIAL', 'Trial'), ('ALTERATION', 'Alteration'), ('READY', 'Ready'), ('DELIVERED', 'Delivered')], default='ASSIGNED', max_length=20)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('expected_completion_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_productions', to=settings.AUTH_USER_MODEL)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='boutiques.boutique')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='orders.order')),
                ('tailor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_productions', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
