# Generated by Django 6.0.6 on 2026-08-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('colors', models.CharField(blank=True, max_length=255)),
                ('fabric', models.CharField(blank=True, max_length=150)),
                ('silhouette', models.CharField(blank=True, max_length=150)),
                ('inspiration_image', models.ImageField(blank=True, null=True, upload_to='custom_designs/inspiration/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWING', 'Reviewing'), ('DESIGNING', 'Designing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_design_requests', to='customers.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
